-- MySQL Script generated by MySQL Workbench
-- Updated version with enhanced features
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema master_floor_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `master_floor_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `master_floor_db`;

-- -----------------------------------------------------
-- Table `master_floor_db`.`partner_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `master_floor_db`.`partner_categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `min_annual_turnover` DECIMAL(15,2) NULL DEFAULT 0,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_name` (`category_name` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `master_floor_db`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `master_floor_db`.`partners` (
  `partner_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  `partner_type` VARCHAR(50) NOT NULL,
  `category_id` INT NULL,
  `director` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `legal_address` TEXT NULL DEFAULT NULL,
  `actual_address` TEXT NULL DEFAULT NULL,
  `inn` VARCHAR(20) NULL DEFAULT NULL,
  `kpp` VARCHAR(20) NULL DEFAULT NULL,
  `ogrn` VARCHAR(20) NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `status` ENUM('active', 'inactive', 'blocked') NOT NULL DEFAULT 'active',
  `last_order_date` DATE NULL DEFAULT NULL,
  `manager_notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`partner_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_partner_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `master_floor_db`.`partner_categories` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 55 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `master_floor_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `master_floor_db`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `category` VARCHAR(100) NULL,
  `unit` VARCHAR(20) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `min_order_quantity` INT NULL DEFAULT 1,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `master_floor_db`.`discount_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `master_floor_db`.`discount_rules` (
  `rule_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category_id` INT NULL,
  `min_quantity` INT NOT NULL,
  `max_quantity` INT NULL,
  `discount_percentage` DECIMAL(5,2) NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`rule_id`),
  CONSTRAINT `fk_rule_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `master_floor_db`.`partner_categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `master_floor_db`.`sales_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `master_floor_db`.`sales_history` (
  `sale_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `partner_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `discount_percentage` DECIMAL(5,2) NULL DEFAULT 0,
  `final_price` DECIMAL(10,2) NOT NULL,
  `sale_date` DATE NOT NULL,
  `payment_status` ENUM('pending', 'paid', 'cancelled') NOT NULL DEFAULT 'pending',
  `payment_date` DATE NULL,
  `invoice_number` VARCHAR(50) NULL,
  `notes` TEXT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sales_partner_idx` (`partner_id` ASC) VISIBLE,
  INDEX `fk_sales_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_partner`
    FOREIGN KEY (`partner_id`)
    REFERENCES `master_floor_db`.`partners` (`partner_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `master_floor_db`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 37 DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `master_floor_db`.`partner_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `master_floor_db`.`partner_contacts` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `partner_id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `position` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `is_primary` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`contact_id`),
  INDEX `fk_contact_partner_idx` (`partner_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_partner`
    FOREIGN KEY (`partner_id`)
    REFERENCES `master_floor_db`.`partners` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert initial partner categories
-- -----------------------------------------------------
INSERT INTO `master_floor_db`.`partner_categories` 
(`category_name`, `description`, `min_annual_turnover`) VALUES
('Bronze', 'Начальный уровень партнерства', 0),
('Silver', 'Средний уровень партнерства', 1000000),
('Gold', 'Продвинутый уровень партнерства', 5000000),
('Platinum', 'Премиум уровень партнерства', 10000000);

-- -----------------------------------------------------
-- Insert initial discount rules
-- -----------------------------------------------------
INSERT INTO `master_floor_db`.`discount_rules`
(`name`, `category_id`, `min_quantity`, `max_quantity`, `discount_percentage`, `is_active`) VALUES
('Базовая скидка Bronze', 1, 1, 1000, 5.00, TRUE),
('Базовая скидка Silver', 2, 1, 1000, 7.00, TRUE),
('Базовая скидка Gold', 3, 1, 1000, 10.00, TRUE),
('Базовая скидка Platinum', 4, 1, 1000, 15.00, TRUE);
